"""members table

Revision ID: fa913fe3a462
Revises: d71eb5f43c02
Create Date: 2026-04-27 17:49:10.386844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa913fe3a462'
down_revision = 'd71eb5f43c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_member_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_name'))
        batch_op.drop_index(batch_op.f('ix_member_email'))

    op.drop_table('member')
    # ### end Alembic commands ###
